[CAMERA]
exposure = 40.0
fps = 50.0
img_num = 200

[MOTOR]
controllername = "C-884.DB"
stages = ["M-126.PD2", "M-126.PD2", "M-126.PD2", "NOSTAGE"]
refmodes = ["FNL", "FRF"]
serialnum = "0000000000"

[AXES]
x = 1
y = 3
z = 2

[VERTEX]
pt1 = [2.0, 6.0]
pt2 = [14.0, 14.0]

[MOVEMENT]
dx = 0.3
dy = 0.5
dz = 0.00025
z_max_step = 150

[FOCUS]
z_min = 1.33300
z_max = 2.5000
step_coarse = 10
step_fine = 20
step_finer = 120
step_num = 1

[OD]
buffer_size = 10
d_cells = 40
d_boundary = 10


[FILE]
save_dir = "frames"
model_path = "model/cell.pt"


[EN]
auto_focus = true
object_detection = true
dynamic_exposure = false
depth = false
