[CAMERA]
exposure = 40.0
fps = 50.0
img_num = 200

[MOTOR]
controllername = "C-884.DB"
stages = ["M-126.PD2", "M-126.PD2", "M-126.PD2", "NOSTAGE"]
refmodes = ["FNL", "FRF"]
serialnum = "0000000000"

[AXES]
x = 1
y = 2
z = 3

[VERTEX]
pt1 = [11.0, 1.0]
pt2 = [14.5, 5.0]

[MOVEMENT]
dx = 0.3
dy = 0.5
dz = 0.00025
z_max_step = 150

[FOCUS]
z_min = 1.33300
z_max = 2.5000
step_coarse = 30
step_fine = 20
step_finer = 10
step_num = 10

[OD]
buffer_size = 10
d_cells = 40
d_boundary = 10

[FILE]
save_dir = "./output"
model_path = "model/cell.pt"


[EN]
auto_focus = false
object_detection = false
sanitize = false
depth = false
